default:
  image: php:7.4-alpine
  
  before_script:
    - apk add --no-cache libzip-dev zip
    - docker-php-ext-install zip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install

test:
  script:
    - php composer.phar run-script test
